module Indicators where

import Databases
import Data.List

-----------------------------------------------------------------------
--
-- Indicators...
--
-- Noise words are removed completely from the indicators lists and from 
-- the text being tested.
-- The words in Ind1 count as indicators in their own right but may also
-- form components (qualifiers, adverbs...) of longer indicators
-- made from each of a. noise words, b. Ind1 words and c. Ind2 words.
-- E.g. "in a terrible mess".
-- The elements of each Ind1 list are strings.
--
-- The main indicators are in the Ind2 lists and these may contain multiple
-- words. For this reason they are mapped to lists of words when they're
-- stemmed (i.e. map (stemAll . words) in IndicatorPredicates).
--
-- It's not perfect, e.g. if "in" is in Ind1 and "found in" is in Ind2
-- then "found" is seen as a 'middleLetters' indicator even though it's 
-- missing the "in" - a false positive. We might code it this way to 
-- catch also "found within", "found inside"..., in order to avoid false 
-- negatives.
--

defNoise
  = ["a",
     "after",
     "an",
     "it",
     "it's",
     "that",
     "that's",
     "the",
     "there's",
     "these",
     "they",
     "this",
     "up",
     "we",
     "who",
     "who's",
     "which"]

defRNoise
  = defNoise \\ prefixNoiseWords
  
defInd1
  = ["about",
     "and",
     "are",
     "as",
     "at",
     "be",
     "been",
     "being",
     "but",
     "by",
     "can",
     "come",
     "did",
     "direct",
     "does",
     "enough",
     "from",
     "has",
     "have",
     "is",
     "get",
     "going",
     "got",
     "if",
     "in",
     "its",
     "let",
     "like",
     "now",
     "on",
     "of",
     "require",
     "so",
     "take",
     "to",
     "took",
     "was",
     "when",
     "who",
     "who's",
     "with",
     "within"]

defInd1R
  = defInd1 \\ prefixNoiseWords

defInd2
  = ["appear",
     "became",
     "become",
     "brings",
     "cause",
     "come",
     "display",
     "find",
     "for",
     "found",
     "gain",
     "get",
     "give",
     "gives",
     "giving",
     "in which",
     "lead",
     "leaving this",
     "let",
     "may",
     "maybe",
     "might",
     "must",
     "made",
     "make",
     "makes",
     "mark",
     "mean",
     "need",
     "obtain",
     "or",
     "produces",
     "provide",
     "reach",
     "required",
     "result",
     "see",
     "seen",
     "show",
     "signal",
     "supply",
     "wield",
     "yield"]

anagramNoise
  = ["a",
     "after",
     "all",
     "an",
     "be",
     "been",
     "being",
     "by",
     "but",
     "for",
     "from",
     "get",
     "go",
     "goes",
     "going",
     "gone",
     "has",
     "in",
     "into",
     "is",
     "it",
     "let",
     "of",
     "require",
     "some",
     "the",
     "that's",
     "that",
     "to",
     "together",
     "up",
     "was",
     "way",
     "when",
     "which",
     "while",
     "whilst",
     "who",
     "who's",
     "will",
     "very"]

anagramInd1
  = ["about",
     "abnormal",
     "awful",
     "bad",
     "change",
     "different",
     "difficult",
     "disorder",
     "frightful",
     "gay",
     "ghastly",
     "horrible",
     "ill",
     "incredible",
     "nasty",
     "new",
     "nouveau",
     "novel",
     "riotous", 
     "rough", 
     "sad", 
     "strange", 
     "poor",
     "terrible",
     "out"]

--
-- Note: revise and reverse get stemmed to 'rev', so this
-- is picked up as an edge case in the solver.
--
anagramInd2
  = ["abandon",
     "aberrate",
     "abnormal",
     "abominable",
     "about",
     "abroad",
     "abstract",
     "absurd",
     "abuse",
     "abysmal",
     "accident",
     "acrobatic",
     "action",
     "active",
     "adapt",
     "addled",
     "adjust",
     "administer",
     "ado",
     "adrift",
     "adulterate",
     "adverse",
     "affect",
     "afflict",
     "afresh",
     "after a fashion",
     "aggravate",
     "aggrieve",
     "agile",
     "agitate",
     "ail",
     "alien",
     "all over the place",
     "alter",
     "alternative",
     "amazing",
     "amend",
     "amended",
     "amendment",
     "amiss",
     "amok",
     "amorphous",
     "amuse",
     "analysis",
     "anarchic",
     "anew",
     "angry",
     "state of anger",
     "state of anger",
     "animated",
     "annoy",
     "anomalous",
     "anomaly",
     "another",
     "antagonize",
     "antic",
     "anxious",
     "anyhow",
     "anyway",
     "approximate",
     "arbitrary",
     "architecture",
     "around",
     "arouse",
     "arrange",
     "arrangement",
     "art",
     "artful",
     "artifice",
     "askew",
     "assault",
     "assemble",
     "assembled",
     "assort",
     "assorted",
     "astray",
     "astonish",
     "at odds",
     "at random",
     "at sea",
     "at sixes and sevens",
     "atrocious",
     "attack",
     "attempt",
     "atypical",
     "awful",
     "awkward",
     "awry",
     "babble",
     "bad",
     "badly",
     "baffle",
     "baffled",
     "bake",
     "ballet",
     "bamboozled",
     "bananas",
     "barking",
     "basketcase",
     "bastardization",
     "bats",
     "battered",
     "battle",
     "batty",
     "beat",
     "beaten",
     "beaten up",
     "become",
     "bedlam",
     "befuddle",
     "belted",
     "bend",
     "bendy",
     "bent",
     "berserk",
     "bespoke",
     "bewilder",
     "bicker",
     "bits",
     "bizarre",
     "blast",
     "blasted",
     "blazing",
     "blend",
     "blighted",
     "blithering",
     "blotto",
     "blow",
     "blown up",
     "blunder",
     "bluster",
     "bob",
     "boil",
     "boiled",
     "boisterous",
     "bomb",
     "booby",
     "boozy",
     "botch",
     "bother",
     "bottled",
     "bounce",
     "bound",
     "bow",
     "box",
     "brawl",
     "breach",
     "break",
     "break up",
     "breeze",
     "brew",
     "brewed",
     "broach",
     "broadcast",
     "broken",
     "broth",
     "buckle",
     "buckled",
     "budge",
     "buffalo",
     "buffet",
     "build",
     "building",
     "built",
     "bully",
     "bump",
     "bungle",
     "bungled",
     "burst",
     "bust",
     "bustle",
     "bustling",
     "busy",
     "butcher",
     "by arrangement",
     "by mistake",
     "byzantine",
     "calamity",
     "camouflage",
     "can be",
     "caper",
     "caprice",
     "career",
     "careless",
     "carry on",
     "carve",
     "carved up",
     "cast",
     "casual",
     "cause",
     "cavalier",
     "cavort",
     "cavorting",
     "change",
     "changed",
     "changes shape",
     "changing",
     "chaotic",
     "characters",
     "chemistry",
     "chew",
     "chop",
     "chopped up",
     "choppy",
     "chuck",
     "churn",
     "circulate",
     "circulated",
     "circus",
     "clash",
     "clever",
     "clobber",
     "cloud",
     "clumsy",
     "coarse",
     "cockup",
     "cock up",
     "cocktail",
     "code",
     "collage",
     "collapse",
     "collate",
     "collect",
     "comedy",
     "comical",
     "commotion",
     "compilation",
     "compile",
     "complex",
     "complicate",
     "complicated",
     "compose",
     "composition",
     "compound",
     "comprising",
     "compromise",
     "concealed",
     "conceive",
     "concoct",
     "concoction",
     "confection",
     "configure",
     "conflict",
     "confound",
     "confuse",
     "confused",
     "constituents",
     "construction",
     "construe",
     "contentious",
     "contort",
     "contorted",
     "contradict",
     "contrary",
     "contrast",
     "contrive",
     "contrived",
     "controversy",
     "conversion",
     "convert",
     "converted",
     "converts",
     "convolute",
     "convoluted",
     "convulse",
     "convulsing",
     "cook",
     "cooked",
     "corked",
     "correct",
     "correction",
     "corrupt",
     "could be",
     "counterfeit",
     "cower",
     "crack",
     "cracked",
     "cracked up",
     "crackers",
     "craftily",
     "crafty",
     "cranky",
     "crash",
     "crashed",
     "crazy",
     "create",
     "creep",
     "crime",
     "criminal",
     "cripple",
     "crisis",
     "crooked",
     "crude",
     "crumble",
     "crumbly",
     "crush",
     "crushed",
     "cryptic",
     "cuckoo",
     "cultivate",
     "culture",
     "cunning",
     "cunningly",
     "curdle",
     "cure",
     "curious",
     "cut and paste",
     "daft",
     "damage",
     "damaged",
     "dance",
     "dancing",
     "dash",
     "dashing",
     "deal",
     "debacle",
     "debauch",
     "debris",
     "decadent",
     "decay",
     "deceive",
     "decipher",
     "decline",
     "decode",
     "decompose",
     "deconstruct",
     "defective",
     "deform",
     "deformed",
     "degenerate",
     "delinquent",
     "delirious",
     "delude",
     "demented",
     "demolish",
     "deplorable",
     "deploy",
     "deployed",
     "deprave",
     "derange",
     "deranged",
     "derelict",
     "derive",
     "derived from",
     "describe",
     "desecrated",
     "design",
     "despair",
     "desperate",
     "destroy",
     "destroyed",
     "destruction",
     "desultory",
     "deteriorate",
     "devastate",
     "devastated",
     "develop",
     "developed",
     "deviant",
     "deviate",
     "device",
     "devilish",
     "devious",
     "diabolical",
     "dicky",
     "digest",
     "digress",
     "dilapidated",
     "dilemma",
     "dire",
     "disarray",
     "disaster",
     "discomfort",
     "discompose",
     "disconcert",
     "discord",
     "disease",
     "disengage",
     "disfigure",
     "disfigured",
     "disgrace",
     "disgruntled",
     "disguise",
     "disguised",
     "dished out",
     "dishevelled",
     "disingenuous",
     "disintegrating",
     "disjoint",
     "disjointed",
     "dislocate",
     "dislocated",
     "dislodge",
     "dismantle",
     "dismantled",
     "dismember",
     "disobey",
     "disorder",
     "disorderly",
     "disorganised",
     "disorganized",
     "disorientated",
     "disperse",
     "dispersed",
     "displace",
     "display",
     "dispose",
     "disposition",
     "dispute",
     "disrepair",
     "disrupt",
     "disrupted",
     "dissect",
     "disseminated",
     "dissipate",
     "dissolute",
     "dissolve",
     "distilled",
     "distort",
     "distorted",
     "distract",
     "distraught",
     "distress",
     "distressed",
     "distribute",
     "distributed",
     "distribution",
     "disturb",
     "disturbance",
     "after disturbance",
     "disturbed",
     "dither",
     "diverse",
     "divert",
     "dizzy",
     "doctor",
     "doddery",
     "dodge",
     "dodgy",
     "done",
     "dotty",
     "doubt",
     "drag",
     "dreadful",
     "dress",
     "dressed",
     "drift",
     "drifting",
     "drive",
     "drunk",
     "dubious",
     "dud",
     "duff",
     "dynamic",
     "easily",
     "eccentric",
     "eccentried",
     "ecstasy",
     "edgy",
     "edit",
     "effect",
     "elaborate",
     "elastic",
     "else",
     "embroidered",
     "embroil",
     "emendation",
     "emerge",
     "energy",
     "engage",
     "engendering",
     "engineer",
     "enigma",
     "ensemble",
     "entangle",
     "entertain",
     "entwine",
     "equivocal",
     "err",
     "errant",
     "erratic",
     "erroneous",
     "erupt",
     "eruption",
     "evolution",
     "evolve",
     "exacerbate",
     "exceptional",
     "exchange",
     "exchanged",
     "excite",
     "excited",
     "excursion",
     "execute",
     "exercise",
     "exercising",
     "exotic",
     "expatiate",
     "explode",
     "exploit",
     "explosive",
     "extraordinary",
     "extravagant",
     "fabricated",
     "fail",
     "fake",
     "fall",
     "false",
     "falter",
     "fanatical",
     "fancy",
     "fantastic",
     "fantasy",
     "fashion",
     "fault",
     "faulty",
     "fermented",
     "fever",
     "fiasco",
     "fickle",
     "fiddle",
     "fiddled",
     "fidget",
     "fierce",
     "figures",
     "finesse",
     "fishy",
     "fitful",
     "fitting",
     "fix",
     "fixed",
     "fizzy",
     "flailing",
     "flaky",
     "flap",
     "flaw",
     "flexible",
     "flexibly",
     "flicker",
     "flighty",
     "flimsy",
     "flirt",
     "flit",
     "floppy",
     "flounce",
     "flounder",
     "floundering",
     "flourish",
     "flow",
     "fluctuate",
     "fluid",
     "flurry",
     "flush",
     "fluster",
     "flustered",
     "flux",
     "fly",
     "flying",
     "fold",
     "foolish",
     "for a change",
     "for revision",
     "for wrestling",
     "forced",
     "foreign",
     "forge",
     "forged",
     "form",
     "formulate",
     "foul",
     "fracture",
     "fractured",
     "fragile",
     "fragment",
     "fragmented",
     "frantic",
     "freak",
     "freaking out",
     "free",
     "freely",
     "frenetic",
     "frenzied",
     "frenzy",
     "fresh",
     "freshly",
     "frightful",
     "frightfully",
     "frisky",
     "frivolous",
     "frolic",
     "frolicsome",
     "fuddled",
     "fudge",
     "funny",
     "furiously",
     "furore",
     "fury",
     "fuse",
     "fuss",
     "gad about",
     "gaffe",
     "gallivant",
     "gambol",
     "gangling",
     "garble",
     "garbled",
     "gauche",
     "gear",
     "generate",
     "generating",
     "germinate",
     "ghastly",
     "gibber",
     "giddily",
     "giddy",
     "giggle",
     "gingerly",
     "glide",
     "gnarl",
     "gnash",
     "go",
     "go off",
     "going crazy",
     "gone",
     "googly",
     "grapple",
     "grate",
     "grave",
     "grief",
     "grim",
     "grind",
     "groggy",
     "groomed",
     "gross",
     "grotesque",
     "ground",
     "group",
     "grow",
     "guise",
     "gyrate",
     "hack",
     "haggard",
     "hallucination",
     "hammer",
     "hammered",
     "handicraft",
     "handiwork",
     "handle",
     "haphazard",
     "harass",
     "harassed",
     "harm",
     "harmed",
     "harry",
     "harsh",
     "hash",
     "hatch",
     "havoc",
     "haywire",
     "hazard",
     "haze",
     "heave",
     "hectic",
     "helpless",
     "helter-skelter",
     "hesitant",
     "hideous",
     "higgledy-piggledy",
     "high",
     "hit",
     "hook",
     "hop",
     "horrible",
     "horribly",
     "horrid",
     "horrific",
     "horse around",
     "horseplay",
     "hotch-potch",
     "hotchpotch",
     "hover",
     "however",
     "hurl",
     "hurt",
     "hybrid",
     "hysteria",
     "idiosyncratic",
     "idiotic",
     "ill",
     "ill bred",
     "ill defined",
     "ill disposed",
     "ill formed",
     "ill treated",
     "illegal",
     "illicit",
     "illusion",
     "imagine",
     "impair",
     "impede",
     "imperfect",
     "impersonate",
     "impolitic",
     "impromptu",
     "improper",
     "improvise",
     "impure",
     "in a ferment",
     "in a jumble",
     "in a mess",
     "in a state",
     "in a way",
     "in a whirl",
     "in disarray",
     "in disguise",
     "in error",
     "in motion",
     "in pieces",
     "in resort",
     "in ruins",
     "in solution",
     "in violation",
     "inaccurate",
     "incoherent",
     "incompetent",
     "incongruous",
     "incorrect",
     "incredible",
     "indecent",
     "indefinite",
     "indirect",
     "indispose",
     "indistinct",
     "individual",
     "indulge",
     "inebriate",
     "inebriated",
     "inept",
     "inexact",
     "infirm",
     "informal",
     "ingenius",
     "ingredients",
     "injure",
     "injured",
     "inordinate",
     "inquietude",
     "insanely",
     "interesting",
     "interfere",
     "interfered with",
     "interpret",
     "intoxicated",
     "intricate",
     "intrigue",
     "invalid",
     "invent",
     "invention",
     "involve",
     "involvement",
     "irregular",
     "irresolute",
     "irritate",
     "irritated",
     "itch",
     "itinerant",
     "jam",
     "jar",
     "jargon",
     "jaunt",
     "jaunty",
     "jazz",
     "jazzy",
     "jerk",
     "jerky",
     "jib",
     "jiggle",
     "jiggling",
     "jitter",
     "jittery",
     "jive",
     "jockey",
     "joke",
     "jolly",
     "jolt",
     "jolting",
     "jostle",
     "jostling",
     "journey",
     "joust",
     "juddering",
     "juggle",
     "jumble",
     "jumbled",
     "jump",
     "jumping",
     "jungle",
     "junk",
     "just",
     "kick",
     "kind",
     "kind of",
     "kinematic",
     "kinetic",
     "kink",
     "kinky",
     "knead",
     "knit",
     "knock",
     "knocked about",
     "knocked out",
     "knot",
     "knotted",
     "labour",
     "laboured",
     "labyrinth",
     "labyrinthine",
     "lament",
     "languid",
     "lark",
     "latent",
     "latitude",
     "lawless",
     "lax",
     "lay",
     "laze",
     "leap",
     "legerdemain",
     "lenient",
     "letters",
     "liberal",
     "liberally",
     "licence",
     "limber",
     "liquid",
     "lissom",
     "lively",
     "loll",
     "loony",
     "loose",
     "loosely",
     "lost",
     "lounge",
     "lousy",
     "ludicrous",
     "lunatic",
     "lurch",
     "machiavellian",
     "machinate",
     "mad",
     "made-up",
     "madness",
     "maelstrom",
     "magic",
     "make",
     "make changes",
     "make changes in",
     "make up",
     "malaise",
     "malcontent",
     "malformation",
     "malformed",
     "malfunction",
     "malicious",
     "malleable",
     "malleably",
     "maltreat",
     "maltreated",
     "manage",
     "managed",
     "mangle",
     "manic",
     "manipulate",
     "manoeuvre",
     "manufacture",
     "manufacturing",
     "mar",
     "marvel",
     "mash",
     "mashed",
     "masked",
     "masquerade",
     "massage",
     "masticate",
     "material",
     "matter",
     "maul",
     "maybe",
     "mayhem",
     "meandering",
     "meddle",
     "medley",
     "melange",
     "melee",
     "melodrama",
     "melt",
     "melted",
     "menace",
     "mend",
     "mental",
     "mercurial",
     "merry",
     "mesh",
     "mess",
     "messy",
     "metamorphosis",
     "might be",
     "migrate",
     "mince",
     "mine",
     "mingle",
     "mint",
     "misbehave",
     "misbehaves",
     "misbehaving",
     "mischief",
     "mischievously",
     "misconduct",
     "misconstrue",
     "misdirect",
     "miserable",
     "misery",
     "misfit",
     "misguided",
     "mishandle",
     "mishandled",
     "mishap",
     "mishmash",
     "misinterpret",
     "mislead",
     "mismanagement",
     "misplace",
     "misprint",
     "misrepresent",
     "misrepresented",
     "misshape",
     "misshapen",
     "misspell",
     "mistake",
     "mistreat",
     "misty",
     "misunderstand",
     "misuse",
     "mix",
     "mix-up",
     "mixed up",
     "mixture",
     "mobile",
     "mobilize",
     "model",
     "modelled",
     "moderate",
     "modification",
     "modify",
     "modulate",
     "mongrel",
     "monstrous",
     "motion",
     "motive",
     "mould",
     "mount",
     "move",
     "movement",
     "moving",
     "muddle",
     "muddled",
     "muff",
     "munching",
     "murky",
     "mush",
     "mushy",
     "mutate",
     "mutation",
     "mutilate",
     "mutilation",
     "mutinous",
     "mutiny",
     "mysterious",
     "nastily",
     "nasty",
     "naughty",
     "neatened",
     "neglect",
     "negotiate",
     "negotiated",
     "nervous",
     "nimble",
     "nobble",
     "nomadic",
     "nonconforming",
     "nonplus",
     "nonsense",
     "nonstandard",
     "not in order",
     "not properly",
     "not right",
     "nuts",
     "nutty",
     "objectionable",
     "oblique",
     "obscene",
     "obscure",
     "obstreperous",
     "odd",
     "oddball",
     "off",
     "offend",
     "onslaught",
     "operate",
     "option",
     "orchestra",
     "ordeal",
     "order",
     "orderly",
     "orders",
     "organisation",
     "organization",
     "organize",
     "organized",
     "orgy",
     "original",
     "originally",
     "ornate",
     "oscillate",
     "ostensible",
     "otherwise",
     "ought to be",
     "out",
     "out of hand",
     "out of joint",
     "out of order",
     "out of place",
     "out of shape",
     "out of sorts",
     "outlandish",
     "outrageous",
     "outwardly",
     "overcome",
     "overhaul",
     "overt",
     "overthrow",
     "overturn",
     "overwhelm",
     "overwrought",
     "palpitate",
     "pan",
     "panic",
     "pants",
     "paradox",
     "paranormal",
     "parody",
     "particular",
     "parts",
     "passion",
     "pastiche",
     "patch",
     "pathetic",
     "pattern",
     "peculiar",
     "peeve",
     "pell-mell",
     "pelt",
     "penal",
     "perform",
     "performing",
     "perhaps",
     "perish",
     "perky",
     "permutation",
     "perpetrate",
     "perplex",
     "perplexed",
     "persecute",
     "persuade",
     "perturb",
     "perverse",
     "perversion",
     "pervert",
     "petulant",
     "phoney",
     "phony",
     "physical jerks",
     "pick out",
     "pick to pieces",
     "pickle",
     "pickled",
     "pie",
     "piecemeal",
     "pieces",
     "pique",
     "pirouette",
     "pitch",
     "pitching",
     "pitiful",
     "pivot",
     "place",
     "plastered",
     "plastic",
     "play",
     "playing",
     "pliably",
     "plight",
     "plot",
     "ply",
     "poke",
     "pooh pooh",
     "poor",
     "poorly",
     "pop",
     "pose",
     "position",
     "possible",
     "possibly",
     "potential",
     "potty",
     "pound",
     "prance",
     "prancing",
     "prank",
     "precarious",
     "predicament",
     "preparation",
     "preparation of",
     "prepare",
     "prepared",
     "press",
     "pretend",
     "primitive",
     "problem",
     "process",
     "processed",
     "produce",
     "profligate",
     "program",
     "propel",
     "protest",
     "provoke",
     "pseudo",
     "pull into line",
     "pull to pieces",
     "pulp",
     "pulverize",
     "pummel",
     "pummelled",
     "punch",
     "punish",
     "push",
     "put in order",
     "put off",
     "put right",
     "put straight",
     "puzzle",
     "puzzling",
     "quaint",
     "quake",
     "quandary",
     "quarrel",
     "queer",
     "question",
     "questionable",
     "quirky",
     "quiver",
     "quivering",
     "rabble",
     "rack",
     "radical",
     "raffish",
     "ragged",
     "rail",
     "raillery",
     "rally",
     "ramble",
     "rambling",
     "rampage",
     "rampant",
     "ramshackle",
     "random",
     "randomly",
     "range",
     "rare",
     "rattle",
     "ratty",
     "ravage",
     "ravaged",
     "raving",
     "raw",
     "re-edit",
     "reaction",
     "rearrange",
     "rearranged",
     "reassemble",
     "reassembled",
     "rebel",
     "rebuild",
     "rebuilt",
     "recalcitrant",
     "recast",
     "recipe",
     "reckless",
     "recollect",
     "recollected",
     "recombine",
     "recondition",
     "reconfigured",
     "reconsider",
     "reconstruct",
     "reconstructed",
     "reconstruction",
     "reconstruction of",
     "recreate",
     "recreated",
     "rectified",
     "rectify",
     "recycle",
     "recycled",
     "redesign",
     "redevelop",
     "redeveloped",
     "redirect",
     "rediscover",
     "redistributed",
     "redraft",
     "redraw",
     "reel",
     "reeling",
     "refashioned",
     "refined",
     "refit",
     "reform",
     "reformed",
     "refurbished",
     "regenerate",
     "regenerated",
     "regrettable",
     "regulated",
     "rehash",
     "reincarnate",
     "rejig",
     "relaunch",
     "relax",
     "relaxed",
     "relay",
     "relocate",
     "remade",
     "remarkable",
     "remodel",
     "rend",
     "render",
     "renew",
     "renovate",
     "renovated",
     "rent",
     "reorder",
     "reorganise",
     "repackage",
     "repair",
     "repaired",
     "replace",
     "replaced",
     "repositioned",
     "represent",
     "reproduce",
     "resettle",
     "resettled",
     "reshaped",
     "reshuffle",
     "resolve",
     "resort",
     "restitution",
     "restless",
     "restoration",
     "restore",
     "restructure",
     "revamp",
     "review",
     "reviewed",
     "revise",
     "revision",
     "revolt",
     "revolting",
     "revolutionary",
     "revolve",
     "rework",
     "rewrite",
     "rewritten",
     "rickety",
     "riddle",
     "ridicule",
     "ridiculous",
     "rig",
     "riot",
     "riotously",
     "rip",
     "ripple",
     "roam",
     "rock",
     "rocky",
     "rogue",
     "roll",
     "rollicking",
     "rolls",
     "rotten",
     "rough",
     "roughly",
     "round",
     "roundabout",
     "rouse",
     "rove",
     "row",
     "rubbish",
     "ruffle",
     "ruin",
     "ruination",
     "rum",
     "rumble",
     "run",
     "runny",
     "run riot",
     "run wild",
     "rupture",
     "ruptured",
     "rustic",
     "sabotage",
     "sack",
     "sad",
     "sadly",
     "salad",
     "savage",
     "scandal",
     "scathe",
     "scatter",
     "scattered",
     "scheme",
     "scraggy",
     "scramble",
     "scrap",
     "scrappy",
     "screw",
     "screwed",
     "screwy",
     "scruffy",
     "scuffle",
     "sculpture",
     "seedy",
     "seesaw",
     "seizure",
     "send",
     "serve",
     "served",
     "set",
     "set in motion",
     "set out",
     "set right",
     "shake",
     "shaken",
     "sham",
     "shambles",
     "shambolic",
     "shape",
     "shaped",
     "shatter",
     "shattered",
     "shift",
     "shifty",
     "shimmer",
     "shimmy",
     "shiver",
     "shock",
     "shocked",
     "shoddy",
     "shoot",
     "shot",
     "shove",
     "shown off",
     "shred",
     "shredded",
     "shudder",
     "shuffle",
     "shuffled",
     "sick",
     "silly",
     "singular",
     "sinuous",
     "sketchy",
     "skip",
     "skittish",
     "slapdash",
     "slaughtered",
     "sleight",
     "slide",
     "slip",
     "sloppy",
     "smack",
     "smash",
     "smashed",
     "smashing",
     "smudge",
     "snarled",
     "solution",
     "solve",
     "somehow",
     "somersault",
     "somewhat",
     "sophisticated",
     "sorry",
     "sort",
     "sort of",
     "soup",
     "sozzled",
     "spank",
     "spasmodic",
     "spattered",
     "special",
     "speculate",
     "spill",
     "spilled",
     "spin",
     "spinning",
     "spirited",
     "splintered",
     "split",
     "spoil",
     "spoilt",
     "sport",
     "sprawl",
     "spray",
     "sprayed",
     "spread",
     "sprightly",
     "spring",
     "sprinkle",
     "spun",
     "spurious",
     "squiffy",
     "squirm",
     "staged",
     "stagger",
     "staggering",
     "stampede",
     "startle",
     "stew",
     "stir",
     "storm",
     "stormy",
     "straighten",
     "strange",
     "strangely",
     "strategy",
     "stray",
     "in a strop",
     "structured",
     "struggle",
     "struggling",
     "stumble",
     "stunt",
     "stupid",
     "stupidly",
     "style",
     "styled",
     "stylistic",
     "substance",
     "substituted",
     "suffer",
     "supple",
     "supply",
     "surgery",
     "surprise",
     "surprising",
     "suspect",
     "swagger",
     "sway",
     "sweep",
     "swept",
     "swilled",
     "swim",
     "swimming",
     "swing",
     "swirl",
     "swirling",
     "switch",
     "switched",
     "synthetic",
     "tackle",
     "tacky",
     "tactics",
     "tailor",
     "tainted",
     "take badly",
     "take by surprise",
     "take ill",
     "take liberties",
     "take wing",
     "tamper",
     "tangle",
     "tawdry",
     "tear",
     "tease",
     "teeter",
     "teetering",
     "temperamental",
     "tempered",
     "terrible",
     "theatrical",
     "thrash",
     "thrashing about",
     "threaten",
     "throb",
     "throw",
     "tickle",
     "tidy",
     "tight",
     "tinker",
     "tipsy",
     "to make",
     "to wrestle",
     "tongue in cheek",
     "topsy turvy",
     "torment",
     "tormented",
     "torn",
     "tortuous",
     "torture",
     "tortured",
     "toss",
     "totter",
     "touchy",
     "tousle",
     "toy",
     "tragic",
     "train",
     "trained",
     "transfer",
     "transform",
     "transformed",
     "transition",
     "translate",
     "translated",
     "translation",
     "transmute",
     "transport",
     "transported",
     "transpose",
     "transposed",
     "trash",
     "trashed",
     "travel",
     "treachery",
     "treat",
     "treated",
     "treatment",
     "tremble",
     "trepidation",
     "trial",
     "tribulation",
     "trick",
     "tricky",
     "trim",
     "trip",
     "trips",
     "trouble",
     "tumble",
     "tumbling",
     "tumult",
     "tumultuous",
     "turbulent",
     "turmoil",
     "turn",
     "turning",
     "tweak",
     "tweaked",
     "twirl",
     "twist",
     "twisted",
     "twitch",
     "type",
     "ugly",
     "unbalanced",
     "unbridled",
     "unbundle",
     "uncanny",
     "uncertain",
     "uncivilised",
     "uncontrolled",
     "unconventional",
     "uncultivated",
     "uncured",
     "undecided",
     "undefined",
     "undisciplined",
     "undone",
     "undulate",
     "unearthly",
     "unexpected",
     "unfaithful",
     "unfamiliar",
     "unfettered",
     "unfit",
     "unfortunate",
     "unfurl",
     "ungainly",
     "ungoverned",
     "unhappy",
     "unhealthy",
     "unkempt",
     "unlawful",
     "unlikely",
     "unnatural",
     "unordered",
     "unorthodox",
     "unpredictable",
     "unprepared",
     "unravel",
     "unravelling",
     "unrecognisable",
     "unrest",
     "unrestrained",
     "unrestricted",
     "unruly",
     "unscrambled",
     "unscrupulous",
     "unseemly",
     "unsettle",
     "unsettled",
     "unsound",
     "unstable",
     "unsteady",
     "untamed",
     "untethered",
     "untidy",
     "untoward",
     "untrained",
     "untrue",
     "untutored",
     "unusual",
     "unwieldy",
     "unwisely",
     "up in the air",
     "up in arms",
     "upheaval",
     "uprise",
     "uproar",
     "upset",
     "vacillate",
     "vacillating",
     "vagrant",
     "vague",
     "vaguely",
     "vandalized",
     "variant",
     "variation",
     "variety",
     "various",
     "vary",
     "veer",
     "venture",
     "versatile",
     "version",
     "vex",
     "vibrate",
     "vicious",
     "vigorous",
     "vigorously",
     "vile",
     "violated",
     "violation of",
     "violent",
     "violently",
     "volatile",
     "wacky",
     "wag",
     "wander",
     "wandering",
     "warp",
     "warped",
     "wasted",
     "wave",
     "waver",
     "wayward",
     "weaved",
     "weird",
     "whack",
     "whip up",
     "whirl",
     "whisk",
     "wicked",
     "wiggle",
     "wild",
     "wind",
     "winding",
     "wise",
     "wobble",
     "wonder",
     "woolly",
     "work",
     "worked",
     "worried",
     "worry",
     "wound",
     "woven",
     "wreck",
     "wrecked",
     "wrestle",
     "wrestling",
     "wretched",
     "wriggle",
     "wring",
     "writhe",
     "writhing",
     "wrong",
     "wrought",
     "yielding",
     "zany"]

anagramInfNoise 
  = anagramNoise

anagramInfInd1
  = anagramInd1

anagramInfInd2
  = map (++ " with") anagramInd2

-- e.g. the little prince
abbreviationsNoise
  = ["a",
     "an",
     "but",
     "extremely",
     "has",
     "the",
     "very",
     "will"]

abbreviationsInd1
  = []

abbreviationsInd2
  = ["abbreviated",
     "abridge",
     "abridged",
     "abrupt",
     "brief",
     "brisk",
     "clip",
     "compact",
     "compressed",
     "concise",
     "condensed",
     "contracted",
     "cursory",
     "curt",
     "curtailed",
     "cut",
     "dinky",
     "ephemeral",
     "euphemistically",
     "flash",
     "fleeting",
     "inconsequential",
     "inconsiderable",
     "inferior",
     "insignificant",
     "lesser",
     "light",
     "little",
     "mini",
     "miniature",
     "minor",
     "minute",
     "negligible",
     "nominal",
     "paltry",
     "peanut",
     "petit",
     "petty",
     "piddling",
     "puny",
     "pruned",
     "quick",
     "rough",
     "short",
     "short-lived",
     "slight",
     "small",
     "snug",
     "spartan",
     "succinct",
     "summary",
     "terse",
     "tiny",
     "to the point",
     "trifling",
     "trivial",
     "truncated"]

oddsNoise
  = ["all",
     "and",
     "appear",
     "at",
     "being",
     "bits",
     "but",
     "has",
     "in",
     "is",
     "it",
     "looks",
     "must",
     "see",
     "seen",
     "seem",
     "show",
     "with",
     "will"]

oddsInd1
  = []

oddsInd2
  = ["50-50",
     "alternately",
     "at odds",
     "brokenly",
     "disconnectedly",
     "discontinuously",
     "even go",
     "even gone",
     "even missing",
     "even without",
     "every other",
     "every so often",
     "fitfully",
     "haphazardly",
     "infrequently",
     "intermittently",
     "irregularly",
     "no even",
     "not even",
     "occasionally",
     "oddly",
     "randomly",
     "regularly",
     "skipping",
     "skippingly",
     "sporadically",
     "uneven",
     "willy-nilly",
     "without even"]

evensNoise
  = oddsNoise

evensInd1
  = []

evensInd2
  = ["50-50",
     "alternately",
     "brokenly",
     "disconnectedly",
     "discontinuously",
     "even",
     "every other",
     "every so often",
     "fitfully",
     "haphazardly",
     "infrequently",
     "intermittently",
     "irregularly",
     "no odds",
     "not odd",
     "occasionally",
     "odd go",
     "odd missing",
     "odds removed",
     "randomly",
     "regularly",
     "removed odds",
     "skipping",
     "skippingly",
     "sporadically",
     "willy-nilly",
     "without odd"]

firstLettersNoise
  = ["a",
     "an",
     "after",
     "all",
     "as",
     "at",
     "but",
     "by",
     "character",
     "end",
     "fall",
     "for",
     "get",
     "has",
     "have",
     "in",
     "is",
     "it",
     "its",
     "letter",
     "of",
     "on",
     "that",
     "that's",
     "the",
     "their",
     "those",
     "though",
     "to", 
     "up",
     "which",
     "who",
     "who's",
     "will",
     "with"]

firstLettersInd1
  = ["bit",
     "first",
     "left",
     "part"]

--
-- Add "less" and you get a last letter indicator
--
lessableFirstLetterWords
  = ["boss",
     "brain",
     "brow",
     "cap",
     "crest",
     "crown",
     "face",
     "hat",
     "head",
     "lead",
     "leader",
     "lid",
     "pilot",
     "point",
     "ridge",
     "root",
     "source",
     "tip",
     "top"]

firstLetterWords
  = ["abridge",
     "abbreviate",
     "abort",
     "about",
     "abstract",
     "almost",
     "alpha",
     "amputate",
     "antecedent",
     "anterior",
     "apex",
     "approximately",
     "arrested",
     "barely",
     "begin",
     "birth",
     "bonnet",
     "boundary",
     "brief",
     "capital",
     "cardinal",
     "ceiling",
     "chief",
     "chip",
     "chop",
     "chunk",
     "clipped",
     "commencement",
     "compress",
     "concussion",
     "condense",
     "contract",
     "cull",
     "curtail",
     "cut",
     "dawn",
     "dash",
     "debut",
     "decrease",
     "defective",
     "deficient",
     "diminish",
     "disbud",
     "drop",
     "early",
     "edge",
     "embryonic",
     "emergence",
     "entrance",
     "entry",
     "essential",
     "facade",
     "first signs",
     "fore",
     "foremost",
     "foreshorten",
     "forward",
     "founding",
     "fragment",
     "front",
     "genesis",
     "good deal of",
     "great deal of",
     "half",
     "hardly",
     "headmost",
     "highest",
     "immature",
     "impaired",
     "imperfect",
     "imprecise",
     "inaccurate",
     "inadequate",
     "inauguration",
     "inception",
     "incomplete",
     "inexact",
     "initially",
     "initiation",
     "introduction",
     "jot",
     "just",
     "kick-off",
     "lacking",
     "launch",
     "lessen",
     "little",
     "mainly",
     "minimally",
     "mostly",
     "mutilate",
     "nearly",
     "nip",
     "north",
     "not entirely",
     "not half",
     "not quite",
     "onset",
     "open",
     "origin",
     "outbreak",
     "outset",
     "outstart",
     "overarch",
     "paramount",
     "pare",
     "peak",
     "piece",
     "pinch",
     "pinnacle",
     "pioneer",
     "precede",
     "precursor",
     "preeminent",
     "prefix",
     "premier",
     "preparatory",
     "primarily",
     "primary",
     "prime",
     "principal",
     "principally",
     "prior",
     "prune",
     "reduced",
     "scrap",
     "segment",
     "shard",
     "shave",
     "short",
     "shred",
     "sketchy",
     "sky",
     "slice","sliver","splinter",
     "snip",
     "snippet",
     "some",
     "source",
     "speck",
     "spot",
     "start",
     "string",
     "stunted",
     "summarise",
     "summary",
     "summit",
     "surface",
     "tip-top",
     "topflight",
     "touch",
     "trace",
     "trifle",
     "trim",
     "truncate",
     "unfinished",
     "upmost",
     "uppermost",
     "west"]

allFirstLetterWords
  = lessableFirstLetterWords ++ firstLetterWords

--
-- Combining subtraction words like "without" with last letter
-- indicators like "end" also yield suitable indicators.
--
firstLettersInd2
  = allFirstLetterWords ++
     [w ++ "less" | w <- lessableLastLetterWords]

lastLettersNoise
  = firstLettersNoise \\ ["end"]

lastLettersInd1
  = ["back",
     "end"]

--
-- Add "less" and you get a first letter indicator
--
lessableLastLetterWords
  = ["bottom",
     "butt",
     "chump",
     "end",
     "heel",
     "hind",
     "limit",
     "rear",
     "rump",
     "seat",
     "tail"]

lastLetterWords
  = ["astern",
     "backside",
     "bound",
     "boundary",
     "buttocks",
     "cessation",
     "climax",
     "close",
     "closure",
     "completion",
     "conclusion",
     "culminate",
     "cropped",
     "death",
     "derriere",
     "doffing cap",
     "east",
     "edge",
     "empty-headed",
     "endpoint",
     "epilogue",
     "essentially",
     "extreme",
     "extremity",
     "face-off",
     "far side",
     "final",
     "finale",
     "finally",
     "finish",
     "finishing touch",
     "floor",
     "foundation",
     "half",
     "hindmost",
     "hindquarters",
     "initial",
     "last",
     "latest",
     "limit",
     "mainly",
     "maturation",
     "mature",
     "mostly",
     "naked",
     "not half",
     "not quite",
     "part",
     "piece",
     "posterior",
     "postern",
     "rearmost",
     "rearward",
     "retrograde",
     "sequel",
     "skimmed",
     "south",
     "start to leave",
     "stoppage",
     "stump",
     "suffices",
     "suffix",
     "summarise",
     "summary",
     "summed",
     "term",
     "terminal",
     "threshold",
     "ultimate",
     "what's behind",
     "winds up"]

allLastLetterWords
  = lessableLastLetterWords ++ lastLetterWords

--
-- Combining subtraction words like "without" with first letter
-- indicators like "head" also yield suitable indicators.
--
lastLettersInd2
  = allLastLetterWords ++
     [w ++ "less" | w <- lessableFirstLetterWords]

middleLettersNoise
  = firstLettersNoise \\ ["in"]

middleLettersInd1
  = ["characters",
     "deep",
     "deep in",
     "deep within",
     "from",
     "in",
     "middle",
     "within"]

lessableMiddleLetterWords
  = ["belly",
     "box",
     "centre",
     "chunk",
     "content",
     "core",
     "gut",
     "heart",
     "soul",
     "spirit",
     "stem",
     "trunk"]

middleLetterWords
  = ["abduct",
     "absorb",
     "accept",
     "accommodate",
     "acquire",
     "across",
     "admit",
     "adopt",
     "allow",
     "amid",
     "amidships",
     "amidst",
     "among",
     "appears",
     "apprehend",
     "appropriate",
     "ascertain",
     "assimilating",
     "assuming",
     "attributes",
     "bagging",
     "bale",
     "bared",
     "beset",
     "besiege",
     "betrayed",
     "binding",
     "bit",
     "bite",
     "blanketing",
     "blockading",
     "bore",
     "bosom",
     "bottle",
     "bowel",
     "boxing",
     "bracketing",
     "bury",
     "caging",
     "camouflage",
     "capture",
     "carry",
     "casing",
     "catch",
     "caught",
     "central",
     "centrum",
     "chambering",
     "claim",
     "clip",
     "closet",
     "clutch",
     "cognize",
     "collection",
     "compassing",
     "component",
     "comprehend",
     "comprising",
     "conceal",
     "conceive",
     "constituents",
     "consuming",
     "contained",
     "contribute",
     "control",
     "cooping",
     "cordoning",
     "corralling",
     "covet",
     "cowling",
     "crash",
     "crating",
     "cuddle",
     "cups",
     "cut",
     "demonstrates",
     "deploy",
     "deployment",
     "deposit",
     "digest",
     "discern",
     "disclosed",
     "discovered",
     "displays",
     "divulged",
     "dress",
     "drink",
     "dwell",
     "eat",
     "element",
     "embodying",
     "embosoming",
     "embrace",
     "employ",
     "encase",
     "encompassing",
     "enfolding",
     "engaging",
     "engulfing",
     "enroll",
     "ensconce",
     "enshrining",
     "enshrouding",
     "entering",
     "entertaining",
     "enthralling",
     "enveloping",
     "environing",
     "enwrapping",
     "epicenter",
     "essence",
     "essential",
     "excerpt",
     "exhibiting",
     "extract",
     "feature",
     "fed",
     "feed",
     "fill",
     "find",
     "finding",
     "found",
     "fragment",
     "furnishing",
     "furniture",
     "gathering",
     "get",
     "give",
     "grapple",
     "grasp",
     "grip",
     "group",
     "guards",
     "gulping",
     "handling",
     "harbouring",
     "harrying",
     "has",
     "have",
     "hedging",
     "held",
     "hemming",
     "hide",
     "hold",
     "holds",
     "hollow",
     "hosting",
     "house",
     "hub",
     "imbibe",
     "imbue",
     "impounding",
     "imprisoning",
     "in",
     "in possession of",
     "include",
     "including",
     "incorporating",
     "inhale",
     "inherent",
     "inject",
     "innards",
     "inner",
     "innermost",
     "inside",
     "install",
     "instill",
     "interior",
     "intermediate",
     "internal",
     "internalise",
     "intrinsic",
     "introduce",
     "investing",
     "involving",
     "inward",
     "jailing",
     "keep",
     "keeping",
     "kennelling",
     "kept",
     "kernel",
     "kidnap",
     "know",
     "lay",
     "learn",
     "letters",
     "lie",
     "limiting",
     "lining",
     "load",
     "locate",
     "lock",
     "lock up",
     "manifest",
     "mantling",
     "masking",
     "middlemost",
     "middling",
     "midland",
     "midmost",
     "midriff",
     "midships",
     "midst",
     "midway",
     "most",
     "munch",
     "nab",
     "nave",
     "nearly",
     "needed",
     "nestle",
     "netting",
     "nip",
     "nub",
     "nuclear",
     "nucleus",
     "observe",
     "obtain",
     "out-take",
     "outed",
     "pack",
     "packaging",
     "palm",
     "park",
     "part",
     "partake",
     "peel",
     "pen",
     "penning",
     "perceive",
     "perch",
     "piece",
     "pierce",
     "pinch",
     "pinpoint",
     "pith",
     "place",
     "plant",
     "pocket",
     "portion",
     "position",
     "possess",
     "prisoners",
     "protecting",
     "providing",
     "put",
     "putt",
     "quarantining",
     "quarter",
     "reach",
     "read",
     "realize",
     "receive",
     "recess",
     "recognize",
     "recruit",
     "reposition",
     "restrain",
     "restricting",
     "retaining",
     "ringing",
     "roofing",
     "sample",
     "seat",
     "secrete",
     "secretly",
     "section",
     "securing",
     "see",
     "seen",
     "segment",
     "seize",
     "selection",
     "sense",
     "served",
     "set",
     "settle",
     "shackled",
     "sheltering",
     "showing",
     "sit",
     "site",
     "situate",
     "slice",
     "smuggle",
     "snap",
     "snatch",
     "snuggle",
     "some",
     "some extent",
     "somewhat",
     "spot",
     "spotted",
     "squash",
     "squeezing",
     "stand",
     "station",
     "steal",
     "stomach",
     "store",
     "storm",
     "stowing",
     "stuff",
     "stuffed with",
     "stuffing",
     "subdivision",
     "substance",
     "supporting",
     "therein",
     "thick",
     "torso",
     "trap",
     "unclogged",
     "unclothe",
     "uncorked",
     "uncovered",
     "undress",
     "unfolded",
     "unfurled",
     "unlatched",
     "unlocked",
     "unmasked",
     "unpacked",
     "unplugged",
     "unrolled",
     "unsealed",
     "unsheathed",
     "unveiled",
     "unwrapped",
     "viscera",
     "vitals",
     "waist",
     "waistline",
     "wear",
     "welcoming",
     "with",
     "witholds",
     "worn",
     "wreathing",
     "yielding"]
 
middleLettersInd2
  = lessableMiddleLetterWords ++ middleLetterWords ++
    [w ++ "less" | w <- lessableEndLetterWords]

endLettersNoise
  = firstLettersNoise

endLettersInd1
  = ["end"]

lessableEndLetterWords
  = ["bank",
     "border",
     "bound",
     "brim",
     "case",
     "core",
     "crust",
     "cover",
     "edge",
     "flange",
     "frame",
     "fringe",
     "hem",
     "limit",
     "lip",
     "rim",
     "rind",
     "shoulder",
     "skin",
     "skirt",
     "strip",
     "tag",
     "wing"]

endLetterWords
  = ["bandage",
     "binder",
     "bare",
     "barren",
     "blank",
     "borderland",
     "bordure",
     "boundaries",
     "brackets",
     "brink",
     "case",
     "circle",
     "circumference",
     "circumscription",
     "coat",
     "cover",
     "crust",
     "curtains",
     "devoid",
     "discontented",
     "disembowel",
     "disembowelled",
     "disheartened",
     "empty",
     "empty-minded",
     "empty-skulled",
     "endmost",
     "envelope",
     "environment",
     "environs",
     "epidermis",
     "evacuate",
     "eviscerate",
     "excavate",
     "exterior",
     "extreme",
     "extremis",
     "extremity",
     "flanks",
     "fringes",
     "gutted",
     "half hearted",
     "hollow",
     "inside out",
     "jacket",
     "janus-like",
     "left and right",
     "margins",
     "outlines",
     "outlying",
     "outside",
     "outskirts",
     "parentheses",
     "peel",
     "perimeter",
     "periphery",
     "pitted",
     "ridges",
     "rind",
     "shell",
     "shore",
     "shoulders",
     "sideline",
     "sides",
     "skin",
     "suburbs",
     "surface",
     "surrounds",
     "tips",
     "two-sided",
     "unfilled",
     "unfulfilled",
     "unoccupied",
     "utmost",
     "vacant",
     "vacation",
     "vacuous",
     "vacuum",
     "verges",
     "void",
     "wrapper",
     "walls"] 

endLettersInd2
  = lessableEndLetterWords ++ endLetterWords ++
    [w ++ "less" | w <- lessableMiddleLetterWords]

duplicateNoise
  = ["a",
     "an",
     "as",
     "but",
     "has",
     "of",
     "over",
     "times",
     "up",
     "will"]

duplicateInd1
  = []

duplicateInd2
  = ["and again",
     "bifold",
     "binary",
     "copy",
     "couple",
     "double", 
     "dual",
     "duplicate",
     "duplex",
     "echo",
     "pair",
     "reiterate",
     "redo",
     "redouble",
     "renew",
     "repeat",
     "retell",
     "retold",
     "repetition",
     "selfsame",
     "two", 
     "twofold",
     "two-faced",
     "two-ply",
     "twice", 
     "twin"]

homophoneNoise
  = ["according",
     "about",
     "as",
     "be",
     "been",
     "being",
     "by",
     "but",
     "come",
     "for",
     "from",
     "in",
     "is",
     "it",
     "it's",
     "like",
     "made",
     "make",
     "may",
     "maybe",
     "might",
     "must",
     "of",
     "on",
     "one",
     "out",
     "people",
     "so",
     "to",
     "the",
     "they",
     "up",
     "way",
     "we",
     "you"]

homophoneInd1
  = ["announced",
     "broadcast",
     "catch",
     "caught",
     "hear", 
     "heard"]

homophoneInd2
  = ["aloud",
     "address",
     "articulate",
     "as we hear",
     "ask",
     "audible",
     "audibly",
     "audience",
     "audience's",
     "audition",
     "auditor",
     "aurally",
     "call",
     "conversation",
     "declared",
     "dictated",
     "dictator's",
     "discussed",
     "expressed",
     "hearsay",
     "conversation",
     "listener",
     "loudly",
     "mouth",
     "narrated",
     "narrator's",
     "noise",
     "noisily",
     "orally",
     "orallist's",
     "overheard",
     "picked",
     "pronounced",
     "radio",
     "read",
     "recital",
     "relate",
     "report",
     "resounded",
     "said",
     "say",
     "sound",
     "speak",
     "speaker's",
     "speaking",
     "speech",
     "spoken",
     "stated",
     "talk",
     "tell",
     "told",
     "utter",
     "verbal",
     "vocal",
     "vociferous",
     "voiced",
     "whisper",
     "wirelessly"]

hyponymNoise
  = ["a",
     "an",
     "as",
     "be",
     "been",
     "being",
     "for",
     "he",
     "has",
     "in",
     "it",
     "of",
     "she",
     "that",
     "that's",
     "the",
     "them",
     "these",
     "they",
     "this",
     "which",
     "who",
     "who's",
     "will"]

hyponymInd1
  = []

hyponymInd2
  = ["could",
     "example",
     "in particular", 
     "instance",
     "kind",
     "may",
     "maybe",
     "might",
     "must",
     "once",
     "one time",
     "particular",
     "perchance",
     "perhaps", 
     "possibly",
     "sample",
     "say",
     "sort",
     "type"]

rotationNoise
  = ["a",
     "an",
     "in",
     "the"]

rotationInd1
  = ["around",
     "circle",
     "cycle",
     "rotate",
     "round",
     "spin"]

rotationInd2
  = ["delay start"]
 
--remove: spring, springs, for
reversalNoise
  = ["a",
     "an",
     "as",
     "after",
     "appears",
     "away",
     "be",
     "been",
     "being",
     "bring",
     "brought",
     "but",
     "call",
     "came",
     "come",
     "do",
     "does",
     "for",
     "get",
     "give",
     "go",
     "goes",
     "going",
     "gone",
     "has",
     "have",
     "held",
     "hold",
     "in",
     "into",
     "is",
     "it",
     "kick",
     "knock",
     "look",
     "lying",
     "making",
     "needed",
     "of",
     "on",
     "put",
     "run",
     "see",
     "seen",
     "send",
     "sent",
     "set",
     "some",
     "take",
     "that",
     "that's",
     "to",
     "the",
     "throw",
     "use",
     "used",
     "was",
     "way",
     "when",
     "which",
     "who",
     "who's",
     "will",
     "write",
     "written"]

reversalInd1
  = ["aback",
     "about",
     "around",
     "over",
     "round",
     "back",
     "up"]

reversalInd2
  = ["about",
     "another way",
     "arising",
     "around",
     "ascendant",
     "ascending",
     "astern",
     "back",
     "backfire",
     "back to front",
     "back-to-front",
     "backsliding",
     "backtracking",
     "backwards",
     "ascend",
     "behind",
     "bending",
     "bent",
     "boomerangs",
     "boosted",
     "capsizing",
     "cast",
     "circle",
     "climb",
     "cocked",
     "comeback",
     "converse",
     "could turn",
     "counter",
     "cartwheel",
     "backflip",
     "doubling",
     "ebbing",
     "elevated",
     "erected",
     "fall",
     "fallback",
     "fixed up",
     "flee",
     "flip",
     "flip-flop",
     "from behind",
     "from below",
     "from east",
     "from right",
     "from back",
     "from bottom",
     "from east",
     "from right",
     "from south",
     "getting round",
     "going back",
     "going north",
     "going round",
     "going up",
     "going north",
     "going west",
     "hauled up",
     "head over heels",
     "heading north",
     "heading west",
     "headlong",
     "hoisted",
     "introvert",
     "inverse",
     "inverted",
     "just opposite",
     "keeling over",
     "kept back",
     "knocked back",
     "left",
     "leftward",
     "lift",
     "mirror",
     "mounting",
     "north",
     "northbound",
     "northerly",
     "northward",
     "on head",
     "reflection",
     "other way",
     "over",
     "overthrown",
     "overturned",
     "promoted",
     "propped",
     "raise",
     "raised",
     "raising",
     "rampant",
     "reacting",
     "read backwards",
     "rear",
     "rearing",
     "rebel",
     "rebound",
     "rebuffed",
     "recalled",
     "recess",
     "recedes",
     "recession",
     "recoiling",
     "recover",
     "recovery",
     "recurrent",
     "reflected",
     "reflex",
     "regressing",
     "rejected",
     "relapse",
     "repelled",
     "repulsed",
     "retiring",
     "retorted",
     "retreat",
     "retrograde",
     "retrogressing",
     "retrospective",
     "retrovert",
     "returning",
     "reverse",
     "reversible",
     "reverting",
     "revolutionary",
     "revolve",
     "right",
     "right-about-face",
     "rise",
     "rises",
     "rising",
     "rocketing",
     "rolling",
     "round",
     "roundabout",
     "running back",
     "from behind",
     "sending back",
     "served up",
     "show up",
     "shown up",
     "shrinking",
     "skied",
     "soaring",
     "somersaulting",
     "spinning",
     "springs",
     "standing",
     "stood up",
     "stuck up",
     "switch",
     "tack",
     "throwback",
     "topsy-turvy",
     "towering",
     "transpose",
     "travelling west",
     "travelling north",
     "turnabout",
     "turnaround",
     "turned",
     "turning",
     "turnover",
     "turns",
     "turns around",
     "twirls",
     "twisted",
     "twisting",
     "upcoming",
     "upended",
     "uplifted",
     "uplifting",
     "upright",
     "uprising",
     "uprooted",
     "upset",
     "upside down",
     "upturn",
     "upwardly mobile",
     "vice versa",
     "west",
     "westerly",
     "westbound",
     "westward",
     "wheeling",
     "withdrawing",
     "written up",
     "wrong way"]

--
-- Must exclude by and with...
--
insertionWordsNoise
  = ["as",
     "be",
     "been",
     "being",
     "but",
     "by",
     "could",
     "come",
     "found",
     "go",
     "going",
     "is",
     "it",
     "may",
     "maybe",
     "might",
     "must",
     "of",
     "part",
     "required",
     "see",
     "seen",
     "set",
     "should",
     "step",
     "that",
     "the",
     "that's",
     "to",
     "was",  
     "which",
     "who",
     "who's"]

--
-- E.g. X entering Y = X entering into Y.
--
insertionWordsInd1
  = ["in",
     "inside",
     "into",
     "within"]

--
-- These capture the notion of one thing being inside another.
-- E.g. amidst X Y => Y in X
-- E.g. X amidst Y => X in Y
-- E.g. X Y amidst => Y in X
--
-- 
-- Adding "by" or "with" to the surroundingWords extends 
-- the list.
-- E.g. X surrounded by Y => X in Y
-- E.g. encased with X Y => Y in X
-- Note: many words that can be followed by either with or into
-- must appear in both insertionWords and surroundingWords.
-- E.g. inject...with, inject...into

--
-- Location words can be associated with around, inside, etc.
-- i.e. both insertionWordsInd1 and surroundingWordsInd1 
-- E.g. find X around Y, find X within Y, round X put Y,
-- in X situate Y, X and Y going round.
--
locationWords
  = ["allow",
     "and",
     "bring",
     "find",
     "getting",
     "held",
     "has",
     "have",
     "hold",
     "in",
     "lay",
     "lie",
     "locate",
     "need",
     "observe",
     "pass",
     "place",
     "plant",
     "position",
     "put",
     "seat",
     "see",
     "seen",
     "set",
     "settle",
     "sit",
     "situate",
     "spot",
     "station",
     "with"]

--
-- Injection words can be associated with into etc. and with.
-- i.e. both insertionWordsInd1 and 'with' 
-- inject X with Y, inject X into Y, X with Y injected,
--
injectionWords
  = ["conceal",
     "crash",
     "cut",
     "eat",
     "ensconce",
     "enroll",
     "entering",
     "fill",
     "imbue",
     "inject",
     "instill",
     "pierce",
     "sandwich",
     "stick",
     "storm",
     "stuff"]

insertionWords
  = locationWords ++
    injectionWords ++
    ["aboard",
     "absorb",
     "admit to",
     "affiliate",
     "amidst",
     "among",
     "amongst",
     "appear in",
     "between",
     "boarding",
     "bore",
     "bought",
     "break",
     "broke",
     "bring",
     "brought",
     "bunking",
     "burst",
     "bury",
     "buy",
     "centre",
     "choke",
     "coated",
     "countersink",
     "countersunk",
     "covered",
     "crash",
     "diving",
     "domiciling",
     "don",
     "drill",
     "drop",
     "during",
     "dwelling",
     "embed",
     "encompassed",
     "engulfed",
     "enlisting",
     "featured",
     "feed",
     "foray",
     "graft",
     "hide",
     "imbed",
     "implant",
     "imported",
     "imprison",
     "included",
     "indoor",
     "inducted",
     "infiltrate",
     "infuse",
     "ingrain",
     "inhabiting",
     "inherent",
     "insert",
     "interior",
     "internal",
     "interrupt",
     "intrinsic",
     "introduced",
     "intrude",
     "invade",
     "invades",
     "invading",
     "involved",
     "inward",
     "living",
     "join",
     "jump",
     "lodging",
     "maraud",
     "midst",
     "nest",
     "occupy",
     "on board",
     "open",
     "participate",
     "penetrate",
     "permeate",
     "pervade",
     "plummet",
     "plunge",
     "put",
     "raid",
     "recess",
     "roosting",
     "secreted",
     "seen",
     "smothered",
     "smuggled",
     "spotted",
     "staying",
     "stop",
     "thrust",
     "transfixed",
     "transplant",
     "trespass",
     "tucked",
     "visit",
     "wearing"]

allInsertionWords
  = insertionWords ++
    [w ++ " by"   | w <- surroundingWords] ++
    [w ++ " with" | w <- surroundingWords] 

-- 
-- E.g. taking = taking ins
-- But we don't want "covered in" - false positive!
--
surroundingWordsNoise
  = (insertionWordsNoise ++ ["in"]) \\ ["has"]

-- 
-- E.g. taken = taken round
-- Also, distfix examples like X in Y surroundgings
--
surroundingWordsInd1
  = ["about",
     "around",
     "environment",
     "protection",
     "surroundings",
     "round"]

--
-- These capture the notion of one thing being around another.
-- E.g. surrounding X Y => X in y
-- E.g. X abducting Y => Y in X
-- E.g. X Y about => X in Y
-- 
-- Adding "by" or "with" to the insertionWords extends 
-- the list.
-- E.g. X pierced by Y => Y in X
-- E.g. stuffed with X Y => X in Y
--
--
-- These can appear distfix with 'with' 
-- E.g. surrounds X with Y, X with Y encircling
-- Includes "in" (dodgy) e.g. X, in Y, meaning put Y in X.
--
envelopingWords
  = ["apprehend",
     "accommodating",
     "admitting",
     "blanketing",
     "bottling",
     "bracketing",
     "bypass",
     "caging",
     "camouflages",
     "carry",
     "casing",
     "choke",
     "cloaking",
     "concealing",
     "cover",
     "dress",
     "embrace",
     "encapsulate",
     "encase",
     "encircle",
     "enshrouding",
     "enveloping",
     "feature",
     "feed",
     "fed",
     "fencing",
     "flanking",
     "framing",
     "hemming",
     "in",
     "pinch",
     "protecting",
     "restrain",
     "ringing",
     "smothering",
     "straddling",
     "surrounding",
     "swaddling",
     "shrouding",
     "taking",
     "wear",
     "worn",
     "wrap"]

surroundingWords
  = locationWords ++
    injectionWords ++
    envelopingWords ++
    ["abduct",
     "absorb",
     "accept",
     "accommodate",
     "acquire",
     "across",
     "admits",
     "adopt",
     "allocate",
     "appreciate",
     "appropriate",
     "ascertain",
     "assign",
     "assimilating",
     "assuming",
     "astride",
     "ate",
     "bagging",
     "bale",
     "beset",
     "besiege",
     "binding",
     "bite",
     "blockading",
     "bore",
     "bought",
     "boxing",
     "bringing",
     "brought",
     "bury",
     "buy",
     "caging",
     "camouflage",
     "capture",
     "carrying",
     "catch",
     "caught",
     "chambering",
     "circling",
     "circumferential",
     "circumscribe",
     "claim",
     "clasp",
     "claw",
     "clench",
     "clinch",
     "closet",
     "cloistering",
     "closing",
     "clutch",
     "coating",
     "cognize",
     "collecting",
     "coming to grips with",
     "compassing",
     "comprehend",
     "comprising",
     "cordoning",
     "concealing",
     "conceive",
     "consuming",
     "containing",
     "control",
     "cooping",
     "corralling",
     "cowling",
     "covet",
     "crating",
     "crossing",
     "cuddle",
     "cups",
     "curtains",
     "delimit",
     "deploy",
     "deposit",
     "describe",
     "devouring",
     "digest",
     "discern",
     "draping",
     "drawing in",
     "drink",
     "eat",
     "embodying",
     "embosoming",
     "employ",
     "enclosing",
     "encompassing",
     "enfolding",
     "engaging",
     "engulfing",
     "enshrining",
     "entertaining",
     "enthralling",
     "environing",
     "enwrapping",
     "fathom",
     "featuring",
     "finding",
     "furnishing",
     "gathering",
     "get",
     "get around",
     "get hold of",
     "get round",
     "get to grips with",
     "give",
     "gobbling",
     "going about",
     "going around",
     "going round",
     "grab",
     "grapple",
     "grasp",
     "grip",
     "guards",
     "gulping",
     "handling",
     "harassing",
     "harbouring",
     "harrying",
     "has",
     "have",
     "have it taped",
     "have knowledge of",
     "having",
     "hedging",
     "held",
     "hide",
     "hold",
     "hooding",
     "hosting",
     "house",
     "hug",
     "imbibe",
     "imprisoning",
     "impounding",
     "in possession of",
     "include",
     "incorporating",
     "inhale",
     "install",
     "internalise",
     "introduce",
     "investing",
     "involving",
     "jailing",
     "kennelling",
     "keeping",
     "kept",
     "kidnap",
     "know",
     "lapping",
     "lashing",
     "learn",
     "limiting",
     "lining",
     "load",
     "lock",
     "lock up",
     "make",
     "makeout",
     "mantling",
     "masking",
     "master",
     "move",
     "munch",
     "nab",
     "neighboring",
     "nestle",
     "netting",
     "nip",
     "obtain",
     "outside",
     "outside of",
     "over",
     "overshadowing",
     "pack",
     "packaging",
     "palm",
     "park",
     "partake",
     "pat",
     "peck",
     "penning",
     "perceive",
     "perch",
     "pinpoint",
     "pocket",
     "possess",
     "post",
     "prehend",
     "putt",
     "quarantining",
     "quarter",
     "reach",
     "read",
     "realize",
     "receive",
     "recognize",
     "recruit",
     "reposition",
     "restricting",
     "retaining",
     "roofing",
     "roundabout",
     "sandwiching",
     "scissor",
     "screening",
     "securing",
     "seen around",
     "seize",
     "sense",
     "shading",
     "sheathing",
     "sheltering",
     "site",
     "smuggle",
     "snap",
     "snatch",
     "snort",
     "snuggle",
     "spanning",
     "spotted",
     "squash",
     "squeezing",
     "stand",
     "steal",
     "store",
     "stowing",
     "stuffing",
     "stuffed with",
     "supporting",
     "surprise",
     "swallowing",
     "swigging",
     "swilling",
     "take",
     "take hold of",
     "tenting",
     "throttle",
     "took",
     "touring",
     "trap",
     "twitch",
     "understand",
     "veiling",
     "walling",
     "welcoming",
     "without",
     "witholds",
     "wreathing"]

allSurroundingWords 
  = surroundingWords ++
    [w ++ " by"   | w <- insertionWords] ++
    [w ++ " with" | w <- insertionWords] 

with
  = ["with"]

withHas
  = ["with", "has", "having"]

-- Here, outside X Y, i.e. put X in Y
insertionInd2L1
  = allSurroundingWords
-- Here, inside X Y, i.e. put Y in X
insertionInd2L2
  = allInsertionWords
-- Here, X inside Y, i.e. put X in Y
insertionInd2C1
  = allInsertionWords
-- Here, X outside Y, i.e. put Y in X
insertionInd2C2
  = allSurroundingWords
-- Here, X Y outside, i.e. put X in Y
insertionInd2R1
  = allSurroundingWords
-- Here, X Y inside, i.e. put Y in X
insertionInd2R2
  = allInsertionWords

leavingWordsNoise
  = ["after",
     "as",
     "associated",
     "be",
     "been",
     "being",
     "but",
     "get",
     "did",
     "got",
     "has",
     "have",
     "may",
     "maybe",
     "might",
     "must",
     "in",
     "is",
     "it",
     "of",
     "on",
     "to",
     "use",
     "was",
     "with",
     "when",
     "will"]

--
-- E.g. departing from
--
leavingWordsInd1
  = ["from"]

--
-- X ind Y means Y - X, e.g. X leaves Y, X escaped from Y
--
leavingWords 
  = ["abandon",
     "abdicate",
     "cease",
     "decamp",
     "depart",
     "desert",
     "escape",
     "exit",
     "flee",
     "jump",
     "leave",
     "left",
     "no longer",
     "out",
     "quit",
     "sack",
     "vacate"] ++
     [w ++ " from" | w <- subtractionWords] 

subtractionWordsNoise
  = ["after",
     "associated",
     "be",
     "been",
     "being",
     "did",
     "get",
     "got",
     "has",
     "have",
     "is",
     "it",
     "longer",
     "may",
     "maybe",
     "might",
     "must",
     "of",
     "there",
     "there's",
     "on",
     "to",
     "use",
     "using",
     "was",
     "with",
     "when",
     "will"]

--
-- E.g. chopping out
--
subtractionWordsInd1
  = ["away",
     "off",
     "out"]

--
-- X ind Y means X - Y, e.g. X abolishing Y, X cutting out Y
--
subtractionWords
  = ["abandon",
     "abdicate",
     "abduct",
     "ablate",
     "abolish",
     "abridge",
     "abscond",
     "absent",
     "abstract",
     "abstraction",
     "all but",
     "amputate",
     "annihilate",
     "annul",
     "aside",
     "aspirate",
     "avoid",
     "away",
     "bail",
     "ban",
     "bar",
     "blow",
     "bone",
     "brief",
     "brush",
     "bur",
     "burl",
     "burr",
     "bury",
     "but for",
     "but not",
     "bypass",
     "cancel",
     "carry",
     "cast",
     "cease",
     "censor",
     "chop",
     "chuck",
     "circumcise",
     "clean",
     "clear",
     "clip",
     "compass",
     "condense",
     "conduct",
     "contract",
     "cream",
     "crumb",
     "cull",
     "curtail",
     "cut",
     "decorticate",
     "deduct",
     "defect",
     "deficit",
     "defuse",
     "delete",
     "demolish",
     "depilate",
     "deport",
     "depose",
     "depreciate",
     "deprive",
     "descale",
     "desorb",
     "diminish",
     "disappear",
     "disburden",
     "discard",
     "discharge",
     "discount",
     "disengage",
     "disjoin",
     "disjoint",
     "dislodge",
     "dismantle",
     "dismiss",
     "disparage",
     "displace",
     "dispose",
     "disregard",
     "dissociate",
     "distant",
     "disunite",
     "ditch",
     "divest",
     "divorce",
     "doesn't",
     "doff",
     "drain",
     "draw",
     "drawn",
     "dredge",
     "drop",
     "dump",
     "efface",
     "eject",
     "eliminate",
     "emigrate",
     "empty",
     "epilate",
     "eradicate",
     "erase",
     "eschew",
     "estrange",
     "evade",
     "evict",
     "eviscerate",
     "except",
     "excise",
     "exclude",
     "exenterate",
     "exit",
     "expel",
     "export",
     "express",
     "expunge",
     "extinguish",
     "extirpate",
     "extract",
     "exude",
     "fall",
     "filter",
     "flee",
     "fleece",
     "flick",
     "fly",
     "forfeit",
     "forget",
     "forgo",
     "forsake",
     "free",
     "give away",
     "go",
     "gone",
     "gut",
     "harvest",
     "hasn't",
     "haul",
     "hook",
     "hull",
     "husk",
     "ignore",
     "inadequate",
     "isolate",
     "jilt",
     "kick",
     "kill",
     "knock",
     "lack",
     "leach",
     "less",
     "let off",
     "let slip",
     "liberate",
     "lift",
     "lose",
     "lost",
     "manhandle",
     "minus",
     "miss",
     "move",
     "muck",
     "nab",
     "neutralise",
     "neutralize",
     "never",
     "nick",
     "no",
     "not",
     "obliterate",
     "off",
     "offload",
     "omit",
     "oust",
     "overlook",
     "pick",
     "pinch",
     "pit",
     "pluck",
     "pull",
     "quell",
     "rack",
     "raze",
     "reduce",
     "reject",
     "release",
     "relinquish",
     "remove",
     "renounce",
     "repel",
     "resect",
     "reserve",
     "resign",
     "retire",
     "retreat",
     "revoke",
     "rid",
     "rip",
     "sack",
     "sacrifice",
     "scalp",
     "scavenge",
     "scoop",
     "scrap",
     "scratch",
     "scrub",
     "seed",
     "sequester",
     "shave",
     "shed",
     "shell",
     "ship",
     "short",
     "shuck",
     "shun",
     "shut",
     "skip",
     "snatch",
     "spew",
     "spoon",
     "spurn",
     "stealing",
     "stem",
     "stolen",
     "strike",
     "strip",
     "struck",
     "subtract",
     "suppress",
     "surrender",
     "take",
     "terminate",
     "throw",
     "tip",
     "toss aside",
     "transfer",
     "transport",
     "trimmed",
     "unburden",
     "undock",
     "undress",
     "unhinge",
     "unobserved",
     "unpack",
     "unseen",
     "unwelcome",
     "vanish",
     "void",
     "want",
     "wash",
     "wasting",
     "weed",
     "winnow",
     "wipe",
     "withdraw",
     "withhold",
     "without",
     "wrest",
     "zap"] 

--
-- E.g. without X Y => Y - X
--
subtractionInd2L1
  = subtractionWords

--
-- E.g. leaving X Y, withdraw from X Y => X - Y
--
subtractionInd2L2
  = leavingWords

--
-- E.g. X leaves Y, X removed from Y => Y - X
--
subtractionInd2C1
  = leavingWords

--
-- E.g. X without Y => X - Y
--
subtractionInd2C2
  = subtractionWords

--
-- Exceptionally rare...
--
subtractionInd2R1
  = []

--
-- E.g. X Y missing => X - Y
--
subtractionInd2R2
  = subtractionWords

-- remove: came, comes
charadeNoise
  = ["a",
     "an",
     "as",
     "be",
     "been",
     "being",
     "came",
     "come",
     "did",
     "does",
     "go",
     "goes",
     "going",
     "gone",
     "is",
     "it",
     "lies",
     "of",
     "put",
     "sits",
     "than",
     "that",
     "the",
     "used",
     "up",
     "was",
     "which",
     "who",
     "who's",
     "will"]

afterWordsNoise
  = charadeNoise ++ ["to", "with"]

afterWordsInd1
  = []

--
-- X ind Y => Y then X
-- E.g. X after Y, X Y following
-- Also include composites using locationWords, e.g.
-- located after, put after...
-- Note: some commute and so appear here and in 
-- the list below.
-- 
afterWords
  = ["abreast",
     "abut",
     "accompany",
     "add",
     "after", 
     "against",
     "alongside",
     "append",
     "associated",
     "behind",
     "below",
     "beneath",
     "concluding",
     "dragging",
     "ensuing",
     "foremost",
     "formerly",
     "following",
     "fronted by",
     "hauling",
     "headed by",
     "hold",
     "lead by",
     "on",
     "opposite",
     "postfix", 
     "preceded by",
     "previous",
     "prop up",
     "pulling",
     "sooner",
     "supported by",
     "under",
     "underfoot",
     "underneath"] ++
     [w ++ " after" | w <- locationWords]

beforeWordsNoise
  = charadeNoise 

beforeWordsInd1
  = ["against",
     "by",
     "on",
     "to",
     "with"]

--
-- X ind Y => X then Y
-- E.g. X before Y, X adjacent to Y
-- 
beforeWords
  = ["above",
     "abreast",
     "abut",
     "accompany",
     "add",
     "adjacent",
     "adjoining",
     "affix",
     "ahead",
     "alongside",
     "and",
     "append",
     "appose",
     "as start",
     "associate",
     "at",
     "attach",
     "attend",
     "before",
     "beside",
     "bond",
     "border",
     "chasing",
     "cleave",
     "clinch",
     "close",
     "coincide",
     "collect",
     "combine",
     "conjoin",
     "connecting",
     "covers",
     "embrace",
     "encounter",
     "facing",
     "fix",
     "followed by",
     "from",
     "front",
     "fuse",
     "gather",
     "get",
     "given",
     "had",
     "has",
     "have",
     "head",
     "held",
     "hit",
     "hook",
     "holding",
     "hug",
     "incur",
     "incurred",
     "initially",
     "involve",
     "interlink",
     "introduce",
     "join",
     "juxtapose",
     "keep",
     "knit",
     "lap",
     "leading",
     "linked",
     "match",
     "meet",
     "merge",
     "met",
     "near",
     "need",
     "neighbour",
     "next",
     "opposite",
     "over",
     "overlook",
     "oversee",
     "pair",
     "participate",
     "plus",
     "perched",
     "precede",
     "prefix",
     "provide",
     "rub",
     "see",
     "show",
     "summon",
     "support",
     "take",
     "then",
     "tie",
     "together",
     "touch",
     "to start",
     "unite",
     "wash"]

charadeInd2L1 
  = afterWords

charadeInd2L2
  = beforeWords

charadeInd2C1 
  = beforeWords

--
-- X ind Y could be intepreted in both ways in this case
-- E.g. X on Y could mean X then Y or X (on Y) => Y then X
--
charadeInd2C2
  = beforeWords ++ afterWords

charadeInd2R1 
  = afterWords

charadeInd2R2
  = beforeWords

